Repository falconlee236/IRC_Server, pull requests merged in 2024-07, with the labels that each got.

#2 [FEAT] 서버 dockerfile 추가
  Dockerfile
  README.md
  src/main.cpp
  start.sh
Labels: enhancement

#3 [FEAT] DOCKER 이미지를 자동으로 해주는 action을 생성
  .github/workflows/docker-image.yml
Labels: enhancement

#5 [fix] docker 파일에 테스트코드 추가
  Dockerfile
  README.md
  src/main.cpp
  start.sh
Labels: bug

#9 [FEAT] main.cpp 코드에 kqueue 추가
  src/main.cpp
Labels: enhancement

#13 [FEAT] Client 클래스 구현
  includes/Client.hpp
  includes/Server.hpp
  src/Client.cpp
  src/Server.cpp
  src/main.cpp
Labels: enhancement

#20 [FEAT] Client class에 기능 추가
  .gitignore
  includes/Client.hpp
  includes/Server.hpp
  input_test
  src/Client.cpp
  src/Server.cpp
Labels: enhancement

#21 [FEAT] MSG 파싱 class 구현
  includes/Client.hpp
  includes/Message.hpp
  includes/Server.hpp
  input_test
  src/Client.cpp
  src/Message.cpp
  src/Server.cpp
Labels: enhancement

#22 [FEAT] NICK command 구현
  Makefile
  includes/Client.hpp
  includes/Message.hpp
  includes/NumericReply.hpp
  includes/Server.hpp
  src/Client.cpp
  src/Message.cpp
  src/Server.cpp
  src/commands/nick.cpp
Labels: enhancement

#23 [FEAT] PASS command 구현
  includes/NumericReply.hpp
  includes/Server.hpp
  input_test
  src/Server.cpp
  src/commands/nick.cpp
  src/commands/pass.cpp
Labels: enhancement

#26 [FEAT] USER command 구현
  includes/Client.hpp
  includes/NumericReply.hpp
  includes/Server.hpp
  src/Client.cpp
  src/Message.cpp
  src/Server.cpp
  src/commands/user.cpp
Labels: feat

#38 [FEAT] Command가 소문자로 들어올때도 인식하게 만들기
  src/Message.cpp
Labels: feat

#29 [FEAT] Channel class 뼈대 구현
  includes/Channel.hpp
  src/Channel.cpp
Labels: feat

#39 [FEAT] welcome 메세지 출력
  includes/Client.hpp
  includes/NumericReply.hpp
  includes/Server.hpp
  src/Client.cpp
  src/Server.cpp
  src/commands/nick.cpp
  src/commands/user.cpp
Labels: feat

#28 [FEAT] QUIT command 구현
  includes/Server.hpp
  src/Server.cpp
  src/commands/quit.cpp
Labels: feat

#40 [FEAT] JOIN command
  includes/Channel.hpp
  includes/Message.hpp
  includes/NumericReply.hpp
  includes/Server.hpp
  src/Channel.cpp
  src/Message.cpp
  src/Server.cpp
  src/commands/join.cpp
Labels: feat

#41 [FEAT] PART command 구현
  includes/Channel.hpp
  includes/NumericReply.hpp
  includes/Server.hpp
  src/Channel.cpp
  src/Server.cpp
  src/commands/join.cpp
  src/commands/part.cpp
Labels: feat

#42 [FEAT] Mode command 구현 + 짜잘한 버그 수정
  includes/Channel.hpp
  includes/NumericReply.hpp
  includes/Server.hpp
  src/Channel.cpp
  src/Server.cpp
  src/commands/join.cpp
  src/commands/mode.cpp
  src/commands/part.cpp
  src/commands/pass.cpp
  src/commands/quit.cpp
Labels: bug, feat

#44 [FEAT] Ping command 구현
  includes/NumericReply.hpp
  includes/Server.hpp
  src/Server.cpp
  src/commands/ping.cpp
Labels: feat

#43 [FEAT] Invite Command 추가 + 작은 버그 수정
  includes/Channel.hpp
  includes/NumericReply.hpp
  includes/Server.hpp
  src/Channel.cpp
  src/Server.cpp
  src/commands/invite.cpp
  src/commands/join.cpp
Labels: bug, feat

#46 [FEAT] Kick command 구현
  includes/Channel.hpp
  includes/NumericReply.hpp
  includes/Server.hpp
  src/Server.cpp
  src/commands/kick.cpp
Labels: feat

#47 [FEAT] PRIVMSG command 구현
  includes/Channel.hpp
  includes/NumericReply.hpp
  includes/Server.hpp
  src/Server.cpp
  src/commands/invite.cpp
  src/commands/kick.cpp
  src/commands/privmsg.cpp
Labels: feat

#49 [FEAT] Bot command 구현 및 큰 버그 해결
  includes/Channel.hpp
  includes/Message.hpp
  includes/NumericReply.hpp
  includes/Server.hpp
  src/Message.cpp
  src/Server.cpp
  src/commands/bot.cpp
  src/commands/part.cpp
  src/commands/privmsg.cpp
  src/commands/topic.cpp
Labels: bug, feat
